language: node_js
node_js:
    - "0.8"

env:
    - secure: "JAYJG0ULcUnuQL6fzuJvdGKLqdLeEflDPA+E3enKHHKNnF1BrZtGp5TfzUXxXN6+hMBB1qRbGfdaxpX5fvrMG7cF/oviiYl0WIa6e+iw425c25+9K70+IpzFxeSNrT/r7XrRfUrjmhtr5MXI05EjAR4VzgrMI9hTThcEqyjGEMM="
    - secure: "iHXolQFukBSkhmbkLw7vF1Tpp7TIvd3rPSGIpK7NGABnZkMBDRFWrv000+NWvub+A25nMBnq7xSKX2dA9RYWfcNse6xy+bFqB7rm4+a9EVlO2h2dWJ2MmpAm3fSJXiO/44jaTe3pwWmbcBOENguIMrvwbC4u7vACuomf7mTdYeQ="

before_script:
    - sudo pip install virtualenv
    - sudo groupadd geodata
    - make all

notifications:
    email:
        recipients:
            - re3-dev@googlegroups.com

